"""LLM-authored strategy variants — INSTRUCTOR USE ONLY.

NOT FOR STUDENT USE. Students should add their strategies as
`was-tournament/wasstrategies/<name>_strategy.py` at the top level
(see sample_strategy.py), NOT in this sub-package.

This directory holds strategies generated by `generate_cloud_strategies.py`
that the instructor has chosen to commit alongside the LLMs' reasoning
traces (`*.json`, `*.thinking.txt`). The tournament runner walks this
sub-package recursively via `pkgutil.walk_packages`, so any axelrod.Player
subclass defined here is auto-discovered alongside the top-level student
strategies.
"""
